FROM node:16-alpine

ENV NODE_ENV production

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY *.json .npmrc ./

# The image set ENV production, but we need the dev deps to build, so install with prod false
RUN npm ci --production=false

# Copy app src
COPY ./src ./src
COPY ./knexfile.ts ./knexfile.ts

RUN npm run build-api

EXPOSE 6540
CMD [ "node", "api-dist/src/api/api.js" ]