version: '3.8'
volumes:
  mssqldata:

services:
  database:
    container_name: uid2_selfserve_mssql
    # image: mcr.microsoft.com/mssql/server:2022-latest
    build:
      context: .
      dockerfile: sqlServer/SqlServerDockerfile
    ports:
      - '11433:1433'
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'yes'
      MSSQL_SA_PASSWORD: 'D3velopmentP0'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P D3velopmentP0 -Q 'SELECT 1'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
  keycloak:
    container_name: uid2_selfserve_keycloak
    image: quay.io/keycloak/keycloak:24.0.0
    environment:
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://database:1433;DatabaseName=keycloak;encrypt=true;trustServerCertificate=true;
      KC_TRANSACTION_XA_ENABLED: 'false'
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: D3velopmentP0
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: D3velopmentP0
      SSP_WEB_HOST: http://localhost:3000
    ports:
      - 18080:8080
      - 19990:9990
    depends_on:
      database:
        condition: service_healthy
    command:
      - start-dev
      - --import-realm
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --health-enabled=true
      - --metrics-enabled=true
      - --spi-connections-jpa-legacy-migration-strategy=update
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
      - ./keycloak/data:/opt/keycloak/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - 11025:1025 # smtp server
      - 18025:8025 # web ui
