version: '3.8'
volumes:
  mssqldata:

services:
  database:
    container_name: uid2_selfserve_mssql
    # image: mcr.microsoft.com/mssql/server:2022-latest
    build:
      context: .
      dockerfile: sqlServer/SqlServerDockerfile
    ports:
      - "11433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      ACCEPT_EULA: "yes"
      MSSQL_SA_PASSWORD: "D3velopmentP0"
    