FROM node:20-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app

# Copy the relevant files for migration neeeds
COPY *.js *.ts *json .npmrc ./
COPY src/api/envars.ts ./src/api/
COPY src/database/migrations/* ./src/database/migrations/

# The image set ENV production, but we need the dev deps to build, so install with prod false
RUN npm ci --production=false
