version: '3.8'
volumes:
  mssqldata:
  loki-data:

services:
  database:
    container_name: uid2_selfserve_mssql
    # image: mcr.microsoft.com/mssql/server:2022-latest
    build:
      context: .
      dockerfile: sqlServer/SqlServerDockerfile
    ports:
      - '11433:1433'
    volumes:
      - mssqldata:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'yes'
      MSSQL_SA_PASSWORD: 'D3velopmentP0'
  keycloak:
    container_name: uid2_selfserve_keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://database:1433;DatabaseName=keycloak;encrypt=true;trustServerCertificate=true;
      KC_TRANSACTION_XA_ENABLED: 'false'
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: D3velopmentP0
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: D3velopmentP0
    ports:
      - 18080:8080
      - 19990:9990
    depends_on:
      - database
    command:
      - start-dev --import-realm --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --spi-theme-welcome-theme=uid2-theme --health-enabled=true --metrics-enabled=true --features=declarative-user-profile
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
  mailhog:
    image: mailhog/mailhog
    ports:
      - 11025:1025 # smtp server
      - 18025:8025 # web ui
  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yml
      - ./loki-data:/tmp/loki
    networks:
      - loki
 
  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./log:/var/log
      - ./config/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
 
  grafana:
    image: grafana/grafana:8.5.5
    ports:
      - "3000:3000"
    networks:
      - loki

networks:
  loki:
