volumes:
  loki-data:

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yml
      - ./loki-data:/tmp/loki
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./log:/var/log
      - ./config/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - '3101:3101'
    environment:
      - GF_SERVER_HTTP_PORT=3101
    networks:
      - loki
