FROM node:latest AS build
WORKDIR /build

COPY *.js *.ts *.json .npmrc /build
RUN npm ci

COPY public/ public
COPY src/ src
RUN npm run build

FROM httpd:alpine
WORKDIR /usr/local/apache2/htdocs/
COPY --from=build /build/build/ .