FROM quay.io/keycloak/keycloak:20.0.3

COPY keycloak/realm/ /opt/keycloak/data/import
COPY keycloak/themes /opt/keycloak/themes

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false", "--spi-theme-welcome-theme=uid2-theme", "--health-enabled=true", "--metrics-enabled=true", "--features=declarative-user-profile"]