FROM quay.io/keycloak/keycloak:20.0.3

# TODO: Once we have a intg and prod dbs, update this
# ENV KC_DB mssql
# ENV KC_DB_URL jdbc:sqlserver://database:1433;DatabaseName=keycloak;encrypt=true;trustServerCertificate=true;
# ENV KC_TRANSACTION_XA_ENABLED 'false'
# ENV KC_DB_USERNAME sa
# ENV KC_DB_PASSWORD D3velopmentP0
# ENV KEYCLOAK_ADMIN admin
# ENV KEYCLOAK_ADMIN_PASSWORD D3velopmentP0

COPY keycloak/realm/ /opt/keycloak/data/import
COPY keycloak/themes /opt/keycloak/themes
RUN /opt/keycloak/bin/kc.sh import --file /opt/keycloak/data/import/realm-export.json --override true; exit 0
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false", "--spi-theme-welcome-theme=uid2-theme"]