FROM node:16-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app

## Install and configure nginx
RUN apk update
RUN apk add nginx
COPY ssportal.conf /etc/nginx/http.d/default.conf
RUN nginx -t 

## Build api code
# Install app dependencies
COPY *.json .npmrc ./
# The image set ENV production, but we need the dev deps to build, so install with prod false
RUN npm ci --production=false
# Copy app src
COPY ./src ./src
COPY ./knexfile.ts ./knexfile.ts

RUN npm run build-api

EXPOSE 80
CMD nginx -g 'pid /tmp/nginx.pid;' & node api-dist/src/api/api.js