volumes:
  loki-data:

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yml
      - ./loki-data:/tmp/loki
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./log:/var/log
      - ./config/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - '3101:3101'
    environment:
      - GF_SERVER_HTTP_PORT=3101
    networks:
      - loki

  agent:
    image: 'grafana/agent:main'
    volumes:
      - '${AGENT_CONFIG_PATH_LOCAL}:${AGENT_CONFIG_PATH}'
      - 'ssportal_logs:${AGENT_LOGS_PATH}'
    # entrypoint:
    #   - '/bin/grafana-agent'
    #   - '-config.file=${AGENT_CONFIG_PATH}/${AGENT_CONFIG_FILE}'
    #   - '-config.expand-env'
    #   - '-config.enable-read-api'
    #   - '-enable-features=integrations-next'
    ports:
      - '3102:3102'
      - '${AGENT_PORT_APP_RECEIVER}:${AGENT_PORT_APP_RECEIVER}'
      # - '${TEMPO_PORT_OTLP_RECEIVER}:${TEMPO_PORT_OTLP_RECEIVER}'
    depends_on:
      # - 'cortex'
      - 'grafana'
      - 'loki'
      # - 'tempo'
