FROM node:latest AS build
ENV NODE_ENV production

WORKDIR /build

COPY *.js *.ts *.json .npmrc /build
RUN npm ci --production=false

COPY public/ public
COPY src/ src
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /build/build/ .