export const analyticsIdentifier = (errorId?: string, errorHash?: string) => {
  if (!errorHash && !errorId) return 'No error identifier';
  return errorHash
    ? `error hash: ${errorHash}` // From backend
    : `error ID: ${errorId}`; // Generated by frontend to make it possible to triage user reported errors.
};
