on:
  workflow_call:

jobs:
  build-ssportal:
    permissions:
      contents: read
      packages: write
    name: Publish API/UI Docker Image
    uses: ./.github/workflows/docker-publish-action.yml
    with:
      IMAGE_NAME: 'iabtechlab/uid2-ssportal' # env context is not available to job.if
      DOCKERFILE: Dockerfile_ssportal
  build-migration:
    permissions:
      contents: read
      packages: write
    name: Publish SSPortal DB migration
    uses: ./.github/workflows/docker-publish-action.yml
    with:
      IMAGE_NAME: 'iabtechlab/uid2-ssportal-migration'
      DOCKERFILE: Dockerfile_ssportal_migration
  build-keycloak:
    permissions:
      contents: read
      packages: write
    name: Publish SSPortal Keycloak
    uses: ./.github/workflows/docker-publish-action.yml
    with:
      IMAGE_NAME: 'iabtechlab/uid2-ssportal-keycloak'
      DOCKERFILE: Dockerfile_keycloak
