on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Get Package Version
        id: version
        run: |
          echo "::set-output name=package_version::$(cat package.json | jq -r '.version')"
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker (${{ inputs.IMAGE_NAME }})
        id: meta-uid2
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ inputs.IMAGE_NAME }}
          tags: |
            type=sha,prefix=${{ steps.version.outputs.package_version }}-,format=short
      - name: Build API
        run: npm run build-api
      - name: Build and push Docker image (${{ inputs.IMAGE_NAME }})
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.DOCKERFILE }}
          push: true
          tags: ${{ steps.meta-uid2.outputs.tags }}
          labels: ${{ steps.meta-uid2.outputs.labels }}
