name: Release Self Serve Portal Image for SSPortal DB migration
run-name: ${{ inputs.release_type == 'Snapshot' && 'Publish Pre-release' || format('Release {0}', inputs.release_type)}} SSPortal DB migration Docker Image by @${{ github.actor }}  
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'The type of release'
        options:
        - Major
        - Minor
        - Patch
        - Snapshot
  pull_request:

jobs:
  Image:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-to-docker-versioned.yaml@v2
    with: 
      release_type: ${{ inputs.release_type }}
      docker_file: Dockerfile_ssportal_migration
      docker_image_name: iabtechlab/uid2-ssportal-migration
      docker_registry: ghcr.io
    secrets: inherit
