name: Self-serve Portal CI
on: workflow_dispatch

jobs:
  check-email-templates:
    runs-on: ubuntu-latest
    name: Check email template updates
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get all email templates that have changed
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            emailTemplates:
              - 'emailTemplates/**.hbs'
    outputs:
      emailTemplatesUpdated: ${{ steps.changed-files.emailTemplates_any_changed }}
  sync-email-templates:
    needs: [check-email-templates]
    name: Sync handlebars template with SendGrid
    if: needs.check-email-templates.outputs.emailTemplatesUpdated == 'true'
    uses: ./.github/workflows/sync-sendgrid-template-action.yml
    with:
      FORCE_SYNC_ALL: 'true'
    secrets:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  build-and-publish-ssportal:
    needs: [sync-email-templates]
    if: always() && (needs.sync-email-templates.result == 'success' || needs.sync-email-templates.result == 'skipped') # Run build and publish ssportal when sync email template is ran or skipped
    uses: ./.github/workflows/docker-publish-ssportal.yml
