name: Trivy Scan
on:
  workflow_call:
    inputs:
      scan_type:
        required: false
        type: string
        default: fs

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vulnerability Scan
        uses: IABTechLab/uid2-shared-actions/actions/vulnerability_scan@v3
        with:
          scan_type: '${{ inputs.scan_type }}'
